// <auto-generated />
using System;
using InstrumentInformation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InstrumentInformation.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240719072022_InitInstruments")]
    partial class InitInstruments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InstrumentInformation.Models.Entity.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiredDatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InstrumentTypeId")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("instruments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5109),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 68,
                            Length = 0.0,
                            Name = "特大号持针钳490",
                            SerialNumber = "0002"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5121),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 68,
                            Length = 0.0,
                            Name = "特大号持针钳490",
                            SerialNumber = "0003"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5122),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 68,
                            Length = 0.0,
                            Name = "特大号持针钳490",
                            SerialNumber = "0004"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5123),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 71,
                            Length = 0.0,
                            Name = "大力抓取钳500",
                            SerialNumber = "das12334ss"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5124),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 71,
                            Length = 0.0,
                            Name = "大力抓取钳500",
                            SerialNumber = "000ds21234432adas4"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5125),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 98,
                            Length = 0.0,
                            Name = "超声刀头550",
                            SerialNumber = "dsada12deas"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5126),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5127),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5128),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5129),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5130),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5130),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5131),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5132),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5133),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDatetime = new DateTime(2024, 7, 19, 15, 20, 22, 147, DateTimeKind.Local).AddTicks(5134),
                            Description = "器械1的描述",
                            ExpiredDatetime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas"
                        });
                });

            modelBuilder.Entity("InstrumentInformation.Models.Entity.InstrumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("instrument_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 47,
                            Name = "荧光内窥镜9L"
                        },
                        new
                        {
                            Id = 48,
                            Name = "荧光内窥镜9S"
                        },
                        new
                        {
                            Id = 49,
                            Name = "电子腹腔镜"
                        },
                        new
                        {
                            Id = 59,
                            Name = "单孔电子腹腔镜"
                        },
                        new
                        {
                            Id = 65,
                            Name = "大号持针钳490"
                        },
                        new
                        {
                            Id = 66,
                            Name = "大号持针钳520"
                        },
                        new
                        {
                            Id = 67,
                            Name = "大号持针钳550"
                        },
                        new
                        {
                            Id = 68,
                            Name = "特大号持针钳490"
                        },
                        new
                        {
                            Id = 69,
                            Name = "特大号持针钳520"
                        },
                        new
                        {
                            Id = 70,
                            Name = "特大号持针钳550"
                        },
                        new
                        {
                            Id = 71,
                            Name = "大力抓取钳500"
                        },
                        new
                        {
                            Id = 72,
                            Name = "大力抓取钳530"
                        },
                        new
                        {
                            Id = 73,
                            Name = "大力抓取钳560"
                        },
                        new
                        {
                            Id = 74,
                            Name = "圆头抓取钳500"
                        },
                        new
                        {
                            Id = 75,
                            Name = "圆头抓取钳530"
                        },
                        new
                        {
                            Id = 76,
                            Name = "圆头抓取钳560"
                        },
                        new
                        {
                            Id = 77,
                            Name = "直剪刀490"
                        },
                        new
                        {
                            Id = 78,
                            Name = "直剪刀520"
                        },
                        new
                        {
                            Id = 79,
                            Name = "直剪刀550"
                        },
                        new
                        {
                            Id = 80,
                            Name = "弯剪刀490"
                        },
                        new
                        {
                            Id = 81,
                            Name = "弯剪刀520"
                        },
                        new
                        {
                            Id = 82,
                            Name = "弯剪刀550"
                        },
                        new
                        {
                            Id = 83,
                            Name = "单极弧剪490"
                        },
                        new
                        {
                            Id = 84,
                            Name = "单极弧剪520"
                        },
                        new
                        {
                            Id = 85,
                            Name = "单极弧剪550"
                        },
                        new
                        {
                            Id = 86,
                            Name = "单极电钩490"
                        },
                        new
                        {
                            Id = 87,
                            Name = "单极电钩520"
                        },
                        new
                        {
                            Id = 88,
                            Name = "单极电钩550"
                        },
                        new
                        {
                            Id = 89,
                            Name = "单极电铲500"
                        },
                        new
                        {
                            Id = 90,
                            Name = "单极电铲530"
                        },
                        new
                        {
                            Id = 91,
                            Name = "单极电铲560"
                        },
                        new
                        {
                            Id = 92,
                            Name = "双极尖头抓钳500"
                        },
                        new
                        {
                            Id = 93,
                            Name = "双极尖头抓钳530"
                        },
                        new
                        {
                            Id = 94,
                            Name = "双极尖头抓钳560"
                        },
                        new
                        {
                            Id = 95,
                            Name = "双极圆头抓钳500"
                        },
                        new
                        {
                            Id = 96,
                            Name = "双极圆头抓钳530"
                        },
                        new
                        {
                            Id = 97,
                            Name = "双极圆头抓钳560"
                        },
                        new
                        {
                            Id = 98,
                            Name = "超声刀头550"
                        },
                        new
                        {
                            Id = 99,
                            Name = "超声刀头510"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
