// <auto-generated />
using System;
using InstrumentInformation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InstrumentInformation.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240719081118_UpdateInsrtumentSeeding")]
    partial class UpdateInsrtumentSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InstrumentInformation.Models.Entity.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("DATE");

                    b.Property<int>("InstrumentTypeId")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsableCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("instruments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(7993),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 68,
                            Length = 0.0,
                            Name = "特大号持针钳490",
                            SerialNumber = "0002",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8004),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 68,
                            Length = 0.0,
                            Name = "特大号持针钳490",
                            SerialNumber = "0003",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8005),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 68,
                            Length = 0.0,
                            Name = "特大号持针钳490",
                            SerialNumber = "0004",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8006),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 71,
                            Length = 0.0,
                            Name = "大力抓取钳500",
                            SerialNumber = "das12334ss",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8007),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 71,
                            Length = 0.0,
                            Name = "大力抓取钳500",
                            SerialNumber = "000ds21234432adas4",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8008),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 98,
                            Length = 0.0,
                            Name = "超声刀头550",
                            SerialNumber = "dsada12deas",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8009),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8009),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8010),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8011),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8012),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8013),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8014),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8015),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8015),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas",
                            UsableCount = 10
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 7, 19, 16, 11, 18, 499, DateTimeKind.Local).AddTicks(8016),
                            Description = "器械1的描述",
                            ExpiredDate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            InstrumentTypeId = 99,
                            Length = 0.0,
                            Name = "超声刀头510",
                            SerialNumber = "45656dadasdas",
                            UsableCount = 10
                        });
                });

            modelBuilder.Entity("InstrumentInformation.Models.Entity.InstrumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("instrument_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 47,
                            Name = "荧光内窥镜9L"
                        },
                        new
                        {
                            Id = 48,
                            Name = "荧光内窥镜9S"
                        },
                        new
                        {
                            Id = 49,
                            Name = "电子腹腔镜"
                        },
                        new
                        {
                            Id = 59,
                            Name = "单孔电子腹腔镜"
                        },
                        new
                        {
                            Id = 65,
                            Name = "大号持针钳490"
                        },
                        new
                        {
                            Id = 66,
                            Name = "大号持针钳520"
                        },
                        new
                        {
                            Id = 67,
                            Name = "大号持针钳550"
                        },
                        new
                        {
                            Id = 68,
                            Name = "特大号持针钳490"
                        },
                        new
                        {
                            Id = 69,
                            Name = "特大号持针钳520"
                        },
                        new
                        {
                            Id = 70,
                            Name = "特大号持针钳550"
                        },
                        new
                        {
                            Id = 71,
                            Name = "大力抓取钳500"
                        },
                        new
                        {
                            Id = 72,
                            Name = "大力抓取钳530"
                        },
                        new
                        {
                            Id = 73,
                            Name = "大力抓取钳560"
                        },
                        new
                        {
                            Id = 74,
                            Name = "圆头抓取钳500"
                        },
                        new
                        {
                            Id = 75,
                            Name = "圆头抓取钳530"
                        },
                        new
                        {
                            Id = 76,
                            Name = "圆头抓取钳560"
                        },
                        new
                        {
                            Id = 77,
                            Name = "直剪刀490"
                        },
                        new
                        {
                            Id = 78,
                            Name = "直剪刀520"
                        },
                        new
                        {
                            Id = 79,
                            Name = "直剪刀550"
                        },
                        new
                        {
                            Id = 80,
                            Name = "弯剪刀490"
                        },
                        new
                        {
                            Id = 81,
                            Name = "弯剪刀520"
                        },
                        new
                        {
                            Id = 82,
                            Name = "弯剪刀550"
                        },
                        new
                        {
                            Id = 83,
                            Name = "单极弧剪490"
                        },
                        new
                        {
                            Id = 84,
                            Name = "单极弧剪520"
                        },
                        new
                        {
                            Id = 85,
                            Name = "单极弧剪550"
                        },
                        new
                        {
                            Id = 86,
                            Name = "单极电钩490"
                        },
                        new
                        {
                            Id = 87,
                            Name = "单极电钩520"
                        },
                        new
                        {
                            Id = 88,
                            Name = "单极电钩550"
                        },
                        new
                        {
                            Id = 89,
                            Name = "单极电铲500"
                        },
                        new
                        {
                            Id = 90,
                            Name = "单极电铲530"
                        },
                        new
                        {
                            Id = 91,
                            Name = "单极电铲560"
                        },
                        new
                        {
                            Id = 92,
                            Name = "双极尖头抓钳500"
                        },
                        new
                        {
                            Id = 93,
                            Name = "双极尖头抓钳530"
                        },
                        new
                        {
                            Id = 94,
                            Name = "双极尖头抓钳560"
                        },
                        new
                        {
                            Id = 95,
                            Name = "双极圆头抓钳500"
                        },
                        new
                        {
                            Id = 96,
                            Name = "双极圆头抓钳530"
                        },
                        new
                        {
                            Id = 97,
                            Name = "双极圆头抓钳560"
                        },
                        new
                        {
                            Id = 98,
                            Name = "超声刀头550"
                        },
                        new
                        {
                            Id = 99,
                            Name = "超声刀头510"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
